version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: yarn run dev

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: yarn run dev
    depends_on:
      - backend
